### ISSUE TITLE
urls.py not compatible with Django 2.1

### ISSUE THREAD

**Issue by jayvdb** [thumbor/libthumbor#40]
```py
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/abuild/rpmbuild/BUILD/libthumbor-1.3.2/libthumbor/django/urls.py", line 4, in <module>
    from django.conf.urls import patterns, url
ImportError: cannot import name 'patterns' from 'django.conf.urls' (/usr/lib/python3.7/site-packages/django/conf/urls/__init__.py)
```

**Comment by heynemann** [comment]
The new version should be compatible with the most up-to-date django. We'll release a version in pypi soon.

**Comment by jayvdb** [comment]
fixed in https://github.com/thumbor/libthumbor/commit/98f8327 and released as noted above.
